plugins {
    id 'java'
}

group = 'dev.hytalemodding'
version = '0.1.0-SNAPSHOT'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

subprojects {
    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenCentral()
    }

    plugins.withType(JavaPlugin).configureEach {
        java {
            toolchain.languageVersion = JavaLanguageVersion.of(25)
        }
    }
}

apply from: 'gradle/abi-manifest.gradle'
